# Generated by Django 5.1 on 2024-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padvantage', models.CharField(max_length=70, verbose_name='advantage')),
            ],
        ),
        migrations.DeleteModel(
            name='pro_advantage',
        ),
    ]
