# Generated by Django 5.1 on 2024-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_proadvantage_delete_pro_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='CompanyName',
            field=models.CharField(default='CompanyName', max_length=50, verbose_name='CompanyName'),
        ),
    ]
